{
    'name': 'Hỗ trợ CRM - Tiến Thọ Book',
    'version': '18.0.0.1',
    'category': 'Helpdesk',
    'summary': "Helpdesk",
    'depends': ['ttb_base', 'ttb_stock', 'ttb_point_of_sale', 'ttb_kpi', 'mail_notify_email_odoo', 'survey', 'hr', 'helpdesk', 'voip', 'web_widget_x2many_2d_matrix'],
    'data': [
         'security/ir.model.access.csv',
         'security/ir_rule.xml',
         'data/ttb_description.xml',
         'data/ir_cron.xml',
         'data/ir_sequence_data.xml',
         'views/ticket_view.xml',
         'views/ttb_happy_call.xml',
         'views/ttb_transaction.xml',
         'views/ttb_related_content.xml',
         'views/ttb_region.xml',
         'views/ttb_branch.xml',
         'views/helpdesk_stage.xml',
         'views/res_partner.xml',
         'views/voip_call.xml',
         'report/helpdesk_crm_report.xml',
         'views/ttb_report_config_views.xml',
        'views/error_ticket_views.xml',
        'views/pos_order.xml',
        'views/ttb_happy_call_rule.xml',
         'views/menu.xml',
         'views/menu_base.xml',
         'views/helpdesk_settings_views.xml',
         'data/config_bao_cao.xml',
        'wizard/ttb_popup_filtered_camera.xml',
         'wizard/ttb_popup_filtered_thanphien.xml',
         'wizard/ttb_popup_filtered_cei.xml',
         'wizard/ttb_popup_filtered_csat.xml',
         'wizard/ttb_popup_filtered_nps.xml',
         'wizard/ttb_popup_filtered_kstt.xml',
         'wizard/ttb_popup_filtered_hpc.xml',
         'wizard/ttb_popup_filtered_dltt.xml',
         'wizard/ttb_popup_filtered_cskh.xml',
    ],
    "assets": {
        "web.assets_backend": [
            "ttb_helpdesk/static/src/**/*",
        ],
    },
    'license': 'LGPL-3',
}
