from . import helpdesk_ticket
from . import ttb_region
from . import ttb_related_content
from . import ttb_happy_call
from . import ttb_transaction
from . import ttb_description
from . import helpdesk_stage
from . import res_partner
from . import hr_department
from . import pos_order
from . import ttb_report_config
from . import error_ticket
from . import helpdesk_settings
from . import helpdesk_ticket_notify
from . import voip_call
from . import ttb_happy_call_rule
