from . import hr_employee
from . import res_users
from . import hr_job
from . import recruitment_requirements
from . import plan_of_recruitment_template
from . import plan_of_recruitment
from . import const
from . import hr_applicant
from . import mail_mail
