from . import purchase_request
from . import purchase_request_line
from . import purchase_batch
from . import purchase_batch_line
from . import purchase_order
from . import purchase_order_line
from . import product_allocation
from . import product_allocation_line
from . import product_allocation_detail
from . import branch
from . import res_partner
from . import stock_move
from . import purchase_price
from . import purchase_price_line
from . import product_product
from . import stock_picking
from . import res_company
from . import res_config_settings
from . import purchase_order_sent_augges
from . import purchase_approval
from . import purchase_approval_line
from . import hang_ton_kho
from . import auto_purchase_request
from . import delivery_order
from . import goods_distribution_ticket
from . import complaint_ticket
from . import advance_request
from . import advance_request_attachment
