{
    'name': 'Đề nghị trả hàng',
    'version': '1.0',
    'summary': 'Quản lý đề nghị trả hàng NCC',
    'author': 'TTB',
    'depends': ['base', 'mail', 'product', 'purchase', 'stock', 'ttb_stock', 'ttb_approval', 'ttb_stock_barcode_incoming',
                'ttb_cancel_request','ttb_purchase',],
    'data': [
        'security/res_groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron_rr_rule.xml',
        'wizard/return_request_add_tax.xml',
        'wizard/return_request_add_discount.xml',
        'views/ttb_return_request.xml',
        'views/plan_return_request.xml',
        'views/report_return_request.xml',
        'views/product_category.xml',
        'wizard/ncc_return_confirm_wizard.xml',
        'views/product_template.xml',
        'views/menu.xml',
        'views/stock_warehouse.xml',
        'views/res_partner.xml',
        'views/stock_picking.xml',
        'views/res_company.xml',
        'wizard/header_template.xml',
        'wizard/print_return_request_supplier.xml',
        'wizard/print_return_request_supplier_documnet.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ttb_return_request/static/src/components/**/*',
        ],
    },
    "license": "LGPL-3",
}
