from . import ttb_kpi_type
from . import ttb_kpi_type_group
from . import ttb_kpi_target
from . import ttb_task_report
from . import ttb_task_category
from . import ttb_task_template
from . import ttb_kpi_template
from . import ttb_kpi_result
from . import pos_config
from . import res_users
from . import ttb_area
from . import hr_employee
from . import ttb_cskhkpi_evaluation_report
from . import ttb_cei_score
from . import cskpi_missing_evaluation_report
from . import vs_result_report
from . import vm_result_report
from . import ttb_kpi_result_branch
from . import ttb_kpi_result_manager
from . import ttb_kpi_result_kvc
from . import ttb_kpi_score_difference
from . import ttb_acceptance_record
from . import confirm_action_wizard
from . import ttb_task_report_approver
from . import branch_checklist_dashboard
from . import my_task
from . import ttb_task_report_line
from . import ttb_task_report_kpi
from . import ttb_tnkhkpi_t2_report
from . import ttb_task_report_delayed
from . import ttb_task_report_mismatch_line
from . import ttb_cancel_reason
from . import ttb_task_report_line_qa_old
from . import ttb_task_report_line_qc_old
from . import ttb_task_report_mismatch_old
