{
    'name': 'KPI - Tiến Thọ Book',
    'version': '18.0.0.1',
    'category': 'Tools',
    'summary': "KPI",
    'depends': ['base', 'hr', 'stock', 'sale_management', 'point_of_sale', 'ttb_sync_sale_augges', 'ttb_product', 'ttb_hr', 'ttb_stock'],
    'data': [
        'data/ir_sequence.xml',
        'data/data.xml',
        'data/cron.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/ttb_kpi_result.xml',
        'views/ttb_kpi_target.xml',
        'views/ttb_kpi_template.xml',
        'views/ttb_kpi_type.xml',
        'views/ttb_kpi_type_group.xml',
        'views/ttb_task_category.xml',
        'views/ttb_task_report.xml',
        'views/ttb_task_template.xml',
        'views/ttb_area.xml',
        'views/res_users.xml',
        'views/pos_config_view.xml',
        'views/hr_employee.xml',
        'views/ttb_cei_score.xml',
        'views/cskpi_missing_evaluation_report.xml',
        'wizard/ttb_popup_filtered.xml',
        'wizard/ttb_task_report_cancel_wizard.xml',
        'views/ttb_cskhkpi_evaluation_report.xml',
        'views/vm_result_report.xml',
        'views/vs_result_report.xml',
        'views/ttb_kpi_result_branch.xml',
        'views/ttb_kpi_result_manager.xml',
        'views/ttb_kpi_result_kvc.xml',
        'views/ttb_kpi_score_difference.xml',
        'views/confirm_action_wizard.xml',
        'views/branch_checklist_dashboard.xml',
        'views/my_task.xml',
        'views/approval_task.xml',
        'views/ttb_tnkhkpi_t2_report.xml',
        'views/ttb_cancel_reason.xml',
        'wizard/recheck_qa_wizard.xml',
        'wizard/recheck_qc_wizard.xml',
        'wizard/choose_result_wizard.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ttb_kpi/static/src/components/**/*',
            'ttb_kpi/static/src/js/branch_checklist_dashboard_graph_field.js',
            'ttb_kpi/static/src/css/index.css',
            'ttb_kpi/static/src/js/quality_action_tag.js',

        ],
    },
    'license': 'LGPL-3',
}
