{
    'name': 'Kế toán  - Tiến Thọ Book',
    'version': '18.0.0.1',
    'category': 'Tools',
    'summary': "Kế toán: Dữ liệu bán dùng xuất hóa đơn điện tử",
    'depends': ['base', 'ttb_purchase', 'stock', 'queue_job', 'point_of_sale', 'ttb_sync_sale_augges', 'ttb_stock_barcode_incoming'],
    'data': [
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'views/res_config_setting_views.xml',
        'views/purchase_invoice_stock.xml',
        'views/purchase_order.xml',
        'views/nimbox_invoice.xml',
        'views/pos_invoice.xml',
        'views/pos_order_views.xml',
        'data/ir_cron.xml',
        'views/stock_picking.xml',
        'views/nibot_api_views.xml',
        'data/nibot_api.xml',
        'views/aggregate_purchase_orders.xml',
        'data/cron_alert_deadline_po.xml',
        'views/report/bao_cao_cong_no_co_hoa_don.xml',
        'views/report/bao_cao_cong_no_khong_co_hoa_don.xml',
        'views/report/invoice_report.xml',
        'views/report/invoice_report_no_nimbox.xml',
        'views/report/menu_item.xml',
        'views/followup_purchase_groupby.xml',
        'views/ttb_mrp_bom_views.xml',
        'views/pos_invoice_schedule_views.xml',
        'views/pos_product_change_views.xml',
        'views/advance_request.xml',
        'templates/einvoice_request_templates.xml',
        'wizard/push_augges_confirm_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ttb_purchase_invoice_stock/static/src/**/*.js',
            'ttb_purchase_invoice_stock/static/src/**/*.xml',
            'ttb_purchase_invoice_stock/static/src/**/*.css',
        ],
    },
    'license': 'LGPL-3',
}
